port: 9080
database:
  host: "localhost"
  port: 6432
  user: "postgresuser"
  password: "postgresPW"
  dbname: "postgresdb"

oidc:
  issuer_url: "https://auth.eegfaktura-dev.duckdns.org/realms/EEGFaktura"
  audience: "at.ourproject.vfeeg.api"
  refresh_interval: "1h"
  refresh_timeout: "10s"

mqtt:
  host: "tcp://localhost:1883"
  id: "edash-backend-2"
  qos: 1

file-content:
  basedir: "../../file-content/"
  templates: "./public"

grpc-provider:
  port: 9092

services:
  mail-server: "localhost:9093"