// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gmodel

type EegModel struct {
	Tenant             *string `json:"tenant,omitempty"`
	SettlementInterval *string `json:"settlementInterval,omitempty"`
	SepaActiv          *bool   `json:"sepaActiv,omitempty"`
}

type Link struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Address string `json:"address"`
}

type Mutation struct {
}

type Query struct {
}
