// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.9
// source: proto/master.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AdminEegService_UpdateValue_FullMethodName = "/at.ourproject.AdminEegService/updateValue"
)

// AdminEegServiceClient is the client API for AdminEegService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminEegServiceClient interface {
	UpdateValue(ctx context.Context, in *UpdateEegRequest, opts ...grpc.CallOption) (*UpdateEegReply, error)
}

type adminEegServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminEegServiceClient(cc grpc.ClientConnInterface) AdminEegServiceClient {
	return &adminEegServiceClient{cc}
}

func (c *adminEegServiceClient) UpdateValue(ctx context.Context, in *UpdateEegRequest, opts ...grpc.CallOption) (*UpdateEegReply, error) {
	out := new(UpdateEegReply)
	err := c.cc.Invoke(ctx, AdminEegService_UpdateValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminEegServiceServer is the server API for AdminEegService service.
// All implementations must embed UnimplementedAdminEegServiceServer
// for forward compatibility
type AdminEegServiceServer interface {
	UpdateValue(context.Context, *UpdateEegRequest) (*UpdateEegReply, error)
	mustEmbedUnimplementedAdminEegServiceServer()
}

// UnimplementedAdminEegServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAdminEegServiceServer struct {
}

func (UnimplementedAdminEegServiceServer) UpdateValue(context.Context, *UpdateEegRequest) (*UpdateEegReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateValue not implemented")
}
func (UnimplementedAdminEegServiceServer) mustEmbedUnimplementedAdminEegServiceServer() {}

// UnsafeAdminEegServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminEegServiceServer will
// result in compilation errors.
type UnsafeAdminEegServiceServer interface {
	mustEmbedUnimplementedAdminEegServiceServer()
}

func RegisterAdminEegServiceServer(s grpc.ServiceRegistrar, srv AdminEegServiceServer) {
	s.RegisterService(&AdminEegService_ServiceDesc, srv)
}

func _AdminEegService_UpdateValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEegRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminEegServiceServer).UpdateValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminEegService_UpdateValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminEegServiceServer).UpdateValue(ctx, req.(*UpdateEegRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminEegService_ServiceDesc is the grpc.ServiceDesc for AdminEegService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminEegService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "at.ourproject.AdminEegService",
	HandlerType: (*AdminEegServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "updateValue",
			Handler:    _AdminEegService_UpdateValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/master.proto",
}
