#!/usr/bin/env bash
# parity-inventory.sh — pull the latest prod vfeeg-backend image,
# compare it against this fork's source tree, and emit a markdown
# report of the gaps.
#
# Inputs (env):
#   PROD_IMAGE_REF  — e.g. ghcr.io/vfeeg-development/vfeeg-backend (no tag)
#   FORK_ROOT       — path to the checked-out fork tree
#   OUT_REPORT      — path where the markdown report is written
#
# Output: writes the report to OUT_REPORT and prints the path.
# Exit code 0 always (the workflow decides what to do with the
# report — non-empty report means open/update an issue).
#
# Methodology documented in
#   memory/project_image_source_recovery.md
# and ADR-0006 (verification mechanism D.1).

set -euo pipefail

: "${PROD_IMAGE_REF:?PROD_IMAGE_REF is required}"
: "${FORK_ROOT:?FORK_ROOT is required}"
: "${OUT_REPORT:?OUT_REPORT is required}"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

echo "=== Resolving latest tag from $PROD_IMAGE_REF ==="
# crane ls returns all tags; pick the highest v-tag (sort by version).
LATEST_TAG=$(crane ls "$PROD_IMAGE_REF" 2>/dev/null \
    | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' \
    | sort -V \
    | tail -1)
if [ -z "$LATEST_TAG" ]; then
    echo "ERROR: no v-tag found at $PROD_IMAGE_REF" >&2
    exit 1
fi
echo "Latest prod tag: $LATEST_TAG"

PROD_REF="${PROD_IMAGE_REF}:${LATEST_TAG}"

echo "=== Exporting image filesystem ==="
crane export "$PROD_REF" "$WORK/image.tar"
ls -lh "$WORK/image.tar"

echo "=== Extracting binary + config (handles literal-backslash entries) ==="
python3 - "$WORK/image.tar" "$WORK" <<'PY'
import os, sys, tarfile
tar_path, work = sys.argv[1], sys.argv[2]
targets = [
    r'usr\local\bin\vfeeg-backend',
    r'etc\backend\config.yaml',
]
with tarfile.open(tar_path, 'r') as t:
    for name in targets:
        try:
            m = t.getmember(name)
        except KeyError:
            # fall back to forward-slash variant (Linux-built images)
            alt = name.replace('\\', '/')
            try:
                m = t.getmember(alt)
            except KeyError:
                print(f'MISS {name}')
                continue
        outpath = os.path.join(work, os.path.basename(name.replace('\\', '/')))
        with t.extractfile(m) as src, open(outpath, 'wb') as dst:
            dst.write(src.read())
        print(f'OK {outpath} ({m.size})')
PY

BIN="$WORK/vfeeg-backend"
CFG="$WORK/config.yaml"
if [ ! -f "$BIN" ]; then
    echo "ERROR: vfeeg-backend binary not extracted" >&2
    exit 1
fi

echo "=== redress source projection ==="
redress source "$BIN" > "$WORK/prod-projection.txt" 2>/dev/null
# Walk the projection in order: each `Package <mod>: <fsPath>` line
# sets the current relative path (strip the `/usr/src/app/` prefix
# that the binary's source map always carries); each `File: <fname>`
# line emits `<relPath>/<fname>`. Anonymous packages (no fsPath, e.g.
# the synthetic main + protobuf indirection packages) are skipped —
# they would otherwise show up as `<file>` without a directory.
awk '
    /^Package / {
        path = ""
        if (match($0, /\/usr\/src\/app\/[^ ]*$/)) {
            path = substr($0, RSTART, RLENGTH)
            sub(/^\/usr\/src\/app\//, "", path)
        }
        next
    }
    /^[ \t]*File: / {
        # Strip leading whitespace and "File: " prefix, then trim trailing whitespace.
        sub(/^[ \t]*File:[ \t]*/, "")
        sub(/[ \t]+$/, "")
        if ($0 == "<autogenerated>" || path == "") next
        print path "/" $0
    }
' "$WORK/prod-projection.txt" | sort -u > "$WORK/prod-files.txt"
echo "prod files (path-qualified): $(wc -l < "$WORK/prod-files.txt")"

echo "=== Fork file set ==="
# %P emits the path relative to the find-root, so output is e.g.
# `database/database.go` — directly comparable to prod's projection.
find "$FORK_ROOT" \
    -type d \( -name vendor -o -name node_modules -o -name .git \) -prune \
    -o -type f -name '*.go' -printf '%P\n' \
    | sort -u > "$WORK/fork-files.txt"
echo "fork files (path-qualified): $(wc -l < "$WORK/fork-files.txt")"

echo "=== go version -m dep dump ==="
# Produce two views per side:
#   *-deps.txt        — full `name@version` (used to detect version drift)
#   *-dep-names.txt   — module path only (used to detect missing modules)
# Missing-module is a structural gap (no transitive presence at all).
# Version drift is a softer signal (might just be a minor bump).
go version -m "$BIN" 2>/dev/null \
    | awk '$1 == "dep" {print $2 "@" $3}' \
    | sort -u > "$WORK/prod-deps.txt"
awk '$1 == "dep" {print $2}' < <(go version -m "$BIN" 2>/dev/null) \
    | sort -u > "$WORK/prod-dep-names.txt"
echo "prod deps: $(wc -l < "$WORK/prod-deps.txt")"

# Fork: parse direct + indirect from go.mod (single-line + parenthesised
# require-blocks). Strip leading `//` for commented-out lines just in case.
awk '
    /^require[[:space:]]*\(/ {flag=1; next}
    flag && /^\)/ {flag=0; next}
    flag && NF >= 2 {print $1 "@" $2; next}
    $1 == "require" && NF >= 3 {print $2 "@" $3; next}
' "$FORK_ROOT/go.mod" \
    | sed 's|^//||' | sort -u > "$WORK/fork-deps.txt"
cut -d@ -f1 < "$WORK/fork-deps.txt" | sort -u > "$WORK/fork-dep-names.txt"
echo "fork deps: $(wc -l < "$WORK/fork-deps.txt")"

echo "=== config keys (top-level only) ==="
if [ -f "$CFG" ]; then
    grep -E '^[a-zA-Z][a-zA-Z0-9_-]*:' "$CFG" \
        | sed 's|:.*||' | sort -u > "$WORK/prod-config-keys.txt"
else
    : > "$WORK/prod-config-keys.txt"
fi
if [ -f "$FORK_ROOT/config.yaml" ]; then
    grep -E '^[a-zA-Z][a-zA-Z0-9_-]*:' "$FORK_ROOT/config.yaml" \
        | sed 's|:.*||' | sort -u > "$WORK/fork-config-keys.txt"
else
    : > "$WORK/fork-config-keys.txt"
fi

echo "=== diff ==="
MISSING_FILES=$(comm -23 "$WORK/prod-files.txt" "$WORK/fork-files.txt" || true)
MISSING_MODULES=$(comm -23 "$WORK/prod-dep-names.txt" "$WORK/fork-dep-names.txt" || true)
# Version drift: modules present in both but with different version.
# Restrict to modules the fork actually requires (intersection of names),
# then keep prod's pinned version where it differs from fork's.
DRIFT_VERSIONS=$(
    comm -12 "$WORK/prod-dep-names.txt" "$WORK/fork-dep-names.txt" \
        | while read -r mod; do
            prod_v=$(awk -F@ -v m="$mod" '$1 == m {print $2; exit}' "$WORK/prod-deps.txt")
            fork_v=$(awk -F@ -v m="$mod" '$1 == m {print $2; exit}' "$WORK/fork-deps.txt")
            if [ -n "$prod_v" ] && [ -n "$fork_v" ] && [ "$prod_v" != "$fork_v" ]; then
                printf '%s: prod=%s fork=%s\n' "$mod" "$prod_v" "$fork_v"
            fi
        done
)
MISSING_CONFIG=$(comm -23 "$WORK/prod-config-keys.txt" "$WORK/fork-config-keys.txt" || true)

# Helper: count non-empty lines of a here-string variable. Returns "0"
# for empty input; never duplicates "0\n0" because no || echo fallback.
count_lines() {
    local v="$1"
    if [ -z "$v" ]; then echo 0; else printf '%s\n' "$v" | grep -c .; fi
}

echo "=== writing report to $OUT_REPORT ==="
{
    echo "# Parity Inventory — \`$PROD_REF\`"
    echo
    echo "Generated $(date -u +'%Y-%m-%dT%H:%M:%SZ') against fork commit \`$(cd "$FORK_ROOT" && git rev-parse --short HEAD)\`."
    echo
    echo "## Summary"
    echo
    printf '| Category | Items missing in fork |\n|---|---|\n'
    printf '| Source files (by name) | %s |\n' "$(count_lines "$MISSING_FILES")"
    printf '| go.mod modules | %s |\n' "$(count_lines "$MISSING_MODULES")"
    printf '| go.mod version drift (module in both, different version) | %s |\n' "$(count_lines "$DRIFT_VERSIONS")"
    printf '| config.yaml top-level keys | %s |\n' "$(count_lines "$MISSING_CONFIG")"
    echo

    if [ -n "$MISSING_FILES" ]; then
        echo "## Source files in prod not in fork"
        echo
        echo "Path-qualified by Go package (relative to module root)."
        echo
        echo '```'
        echo "$MISSING_FILES"
        echo '```'
        echo
        echo "_Known caveat: \`graph/generated/*\` entries (bool.go, string.go, context_field.go, oneshot.go, dtomodel.go, eegmodel.go, registration_model.go etc.) are gqlgen output. Prod uses gqlgen v0.17.90+ which splits the codegen across multiple files; the fork uses an older gqlgen that emits one monolithic \`generated.go\`. These are not source-code gaps — they would auto-appear on a gqlgen version bump + \`go generate\`._"
        echo
    fi

    if [ -n "$MISSING_MODULES" ]; then
        echo "## go.mod modules in prod not in fork"
        echo
        echo "Module paths that the prod binary depends on (direct or transitive) and the fork \`go.mod\` does not list at all."
        echo
        echo '```'
        echo "$MISSING_MODULES"
        echo '```'
        echo
        echo "_Note: this list includes transitive deps from prod. Many will resolve automatically when adding the actual direct deps the fork is missing._"
        echo
    fi

    if [ -n "$DRIFT_VERSIONS" ]; then
        echo "## go.mod version drift"
        echo
        echo "Modules required by both prod and fork but pinned to different versions."
        echo
        echo '```'
        echo "$DRIFT_VERSIONS"
        echo '```'
        echo
        echo "_Action: typically resolved by \`go get <module>@<prod-version>\` followed by \`go mod tidy\`. Verify before bumping (semver-major changes need review)._"
        echo
    fi

    if [ -n "$MISSING_CONFIG" ]; then
        echo "## config.yaml top-level keys in prod not in fork"
        echo
        echo '```'
        echo "$MISSING_CONFIG"
        echo '```'
        echo
    fi

    if [ -z "$MISSING_FILES$MISSING_MODULES$DRIFT_VERSIONS$MISSING_CONFIG" ]; then
        echo "## ✅ No gaps detected"
        echo
        echo "Fork is at functional parity with \`$PROD_REF\` on the dimensions checked here. Per ADR-0006 this does not yet imply full verified parity — D.2/D.3/D.4 checks must also pass."
    fi

    echo
    echo "---"
    echo
    echo "Methodology: ADR-0006 §D.1. Reproducible via \`scripts/parity-inventory.sh\`."
} > "$OUT_REPORT"

echo "Report ready: $OUT_REPORT"
