#!/usr/bin/env bash
# parity-inventory.sh — pull the latest prod vfeeg-backend image,
# compare it against this fork's source tree, and emit a markdown
# report of the gaps.
#
# Inputs (env):
#   PROD_IMAGE_REF  — e.g. ghcr.io/vfeeg-development/vfeeg-backend (no tag)
#   FORK_ROOT       — path to the checked-out fork tree
#   OUT_REPORT      — path where the markdown report is written
#
# Output: writes the report to OUT_REPORT and prints the path.
# Exit code 0 always (the workflow decides what to do with the
# report — non-empty report means open/update an issue).
#
# Methodology documented in
#   memory/project_image_source_recovery.md
# and ADR-0006 (verification mechanism D.1).

set -euo pipefail

: "${PROD_IMAGE_REF:?PROD_IMAGE_REF is required}"
: "${FORK_ROOT:?FORK_ROOT is required}"
: "${OUT_REPORT:?OUT_REPORT is required}"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

echo "=== Resolving latest tag from $PROD_IMAGE_REF ==="
# crane ls returns all tags; pick the highest v-tag (sort by version).
LATEST_TAG=$(crane ls "$PROD_IMAGE_REF" 2>/dev/null \
    | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' \
    | sort -V \
    | tail -1)
if [ -z "$LATEST_TAG" ]; then
    echo "ERROR: no v-tag found at $PROD_IMAGE_REF" >&2
    exit 1
fi
echo "Latest prod tag: $LATEST_TAG"

PROD_REF="${PROD_IMAGE_REF}:${LATEST_TAG}"

echo "=== Exporting image filesystem ==="
crane export "$PROD_REF" "$WORK/image.tar"
ls -lh "$WORK/image.tar"

echo "=== Extracting binary + config (handles literal-backslash entries) ==="
python3 - "$WORK/image.tar" "$WORK" <<'PY'
import os, sys, tarfile
tar_path, work = sys.argv[1], sys.argv[2]
targets = [
    r'usr\local\bin\vfeeg-backend',
    r'etc\backend\config.yaml',
]
with tarfile.open(tar_path, 'r') as t:
    for name in targets:
        try:
            m = t.getmember(name)
        except KeyError:
            # fall back to forward-slash variant (Linux-built images)
            alt = name.replace('\\', '/')
            try:
                m = t.getmember(alt)
            except KeyError:
                print(f'MISS {name}')
                continue
        outpath = os.path.join(work, os.path.basename(name.replace('\\', '/')))
        with t.extractfile(m) as src, open(outpath, 'wb') as dst:
            dst.write(src.read())
        print(f'OK {outpath} ({m.size})')
PY

BIN="$WORK/vfeeg-backend"
CFG="$WORK/config.yaml"
if [ ! -f "$BIN" ]; then
    echo "ERROR: vfeeg-backend binary not extracted" >&2
    exit 1
fi

echo "=== redress source projection ==="
redress source "$BIN" > "$WORK/prod-projection.txt" 2>/dev/null
grep -oE '^File: [^[:space:]]+' "$WORK/prod-projection.txt" \
    | awk '{print $2}' | sort -u > "$WORK/prod-files.txt"
echo "prod files: $(wc -l < "$WORK/prod-files.txt")"

echo "=== Fork file set ==="
find "$FORK_ROOT" \
    -type d \( -name vendor -o -name node_modules -o -name .git \) -prune \
    -o -type f -name '*.go' -printf '%f\n' \
    | sort -u > "$WORK/fork-files.txt"
echo "fork files: $(wc -l < "$WORK/fork-files.txt")"

echo "=== go version -m dep dump ==="
go version -m "$BIN" 2>/dev/null \
    | awk '$1 == "dep" {print $2 "@" $3}' \
    | sort -u > "$WORK/prod-deps.txt"
echo "prod deps: $(wc -l < "$WORK/prod-deps.txt")"

awk '$1 == "require" {flag=1; next} flag && /^\)/ {flag=0} flag {print $1 "@" $2}' \
    "$FORK_ROOT/go.mod" \
    | sed 's|^//||' | sort -u > "$WORK/fork-deps.txt"
echo "fork deps: $(wc -l < "$WORK/fork-deps.txt")"

echo "=== config keys (top-level only) ==="
if [ -f "$CFG" ]; then
    grep -E '^[a-zA-Z][a-zA-Z0-9_-]*:' "$CFG" \
        | sed 's|:.*||' | sort -u > "$WORK/prod-config-keys.txt"
else
    : > "$WORK/prod-config-keys.txt"
fi
if [ -f "$FORK_ROOT/config.yaml" ]; then
    grep -E '^[a-zA-Z][a-zA-Z0-9_-]*:' "$FORK_ROOT/config.yaml" \
        | sed 's|:.*||' | sort -u > "$WORK/fork-config-keys.txt"
else
    : > "$WORK/fork-config-keys.txt"
fi

echo "=== diff ==="
MISSING_FILES=$(comm -23 "$WORK/prod-files.txt" "$WORK/fork-files.txt" \
    | grep -v '^<autogenerated>$' || true)
MISSING_DEPS=$(comm -23 "$WORK/prod-deps.txt" "$WORK/fork-deps.txt" || true)
MISSING_CONFIG=$(comm -23 "$WORK/prod-config-keys.txt" "$WORK/fork-config-keys.txt" || true)

echo "=== writing report to $OUT_REPORT ==="
{
    echo "# Parity Inventory — \`$PROD_REF\`"
    echo
    echo "Generated $(date -u +'%Y-%m-%dT%H:%M:%SZ') against fork commit \`$(cd "$FORK_ROOT" && git rev-parse --short HEAD)\`."
    echo
    echo "## Summary"
    echo
    printf '| Category | Items missing in fork |\n|---|---|\n'
    printf '| Source files (by name) | %s |\n' "$(echo "$MISSING_FILES" | grep -c . || echo 0)"
    printf '| go.mod deps | %s |\n' "$(echo "$MISSING_DEPS" | grep -c . || echo 0)"
    printf '| config.yaml top-level keys | %s |\n' "$(echo "$MISSING_CONFIG" | grep -c . || echo 0)"
    echo

    if [ -n "$MISSING_FILES" ]; then
        echo "## Source files in prod not in fork"
        echo
        echo '```'
        echo "$MISSING_FILES"
        echo '```'
        echo
        echo "_Filename matching only — collision possible if two packages have a like-named file. Use \`redress source\` projection for package-qualified verification._"
        echo
    fi

    if [ -n "$MISSING_DEPS" ]; then
        echo "## go.mod deps in prod not in fork"
        echo
        echo '```'
        echo "$MISSING_DEPS"
        echo '```'
        echo
    fi

    if [ -n "$MISSING_CONFIG" ]; then
        echo "## config.yaml top-level keys in prod not in fork"
        echo
        echo '```'
        echo "$MISSING_CONFIG"
        echo '```'
        echo
    fi

    if [ -z "$MISSING_FILES$MISSING_DEPS$MISSING_CONFIG" ]; then
        echo "## ✅ No gaps detected"
        echo
        echo "Fork is at functional parity with \`$PROD_REF\` on the dimensions checked here. Per ADR-0006 this does not yet imply full verified parity — D.2/D.3/D.4 checks must also pass."
    fi

    echo
    echo "---"
    echo
    echo "Methodology: ADR-0006 §D.1. Reproducible via \`scripts/parity-inventory.sh\`."
} > "$OUT_REPORT"

echo "Report ready: $OUT_REPORT"
